### ISSUE TITLE
UATs are failing with 401 in one-click installation

### ISSUE THREAD

**Issue by kimwnasptd** [canonical/bundle-kubeflow#951]
### Bug Description

After installing CKF in Azure with one-click deployment then some of the UATs are failing with 401 errors. 

Specifically the tests that fail are the ones that try to trigger a Pipeline, so there's a high chance that something is happening with the ServiceAccount that gets injected to the Notebooks (maybe the PodDefault is never created?)

### To Reproduce

1. Deploy CKF on Azure with one-click
2. Run the UATs

### Environment

CKF 1.8 on Azure

### Relevant Log Output

https://pastebin.canonical.com/p/wMJ4TbQQPj/

**Comment by misohu** [comment]
Environment: juju 3.4.4, aks v1.28.9, kubeflow 1.8/stable

I have created the oneclick deployment. I made sure the components are active. 

```
Model     Controller  Cloud/Region       Version  SLA          Timestamp
kubeflow  manual      k8s-cloud/uksouth  3.4.4    unsupported  08:38:56Z

SAAS        Status  Store  URL
grafana     active  local  admin/cos.grafana
prometheus  active  local  admin/cos.prometheus

App                        Version                  Status  Scale  Charm                    Channel          Rev  Address       Exposed  Message
admission-webhook                                   active      1  admission-webhook        1.8/stable       301  10.0.236.178  no       
argo-controller                                     active      1  argo-controller          3.3.10/stable    424  10.0.6.83     no       
dex-auth                                            active      1  dex-auth                 2.36/stable      422  10.0.236.34   no       
envoy                      res:oci-image@cc06b3e    active      1  envoy                    2.0/stable       194  10.0.183.212  no       
grafana-agent-k8s          0.40.4                   active      1  grafana-agent-k8s        latest/edge       80  10.0.200.220  no       logging-consumer: off
istio-ingressgateway                                active      1  istio-gateway            1.17/stable     1000  10.0.180.252  no       
istio-pilot                                         active      1  istio-pilot              1.17/stable     1011  10.0.24.151   no       
jupyter-controller                                  active      1  jupyter-controller       1.8/stable       849  10.0.237.229  no       
jupyter-ui                                          active      1  jupyter-ui               1.8/stable       858  10.0.121.7    no       
katib-controller           res:oci-image@31ccd70    active      1  katib-controller         0.16/stable      576  10.0.33.4     no       
katib-db                   8.0.36-0ubuntu0.22.04.1  active      1  mysql-k8s                8.0/stable       153  10.0.59.17    no       
katib-db-manager                                    active      1  katib-db-manager         0.16/stable      539  10.0.54.131   no       
katib-ui                                            active      1  katib-ui                 0.16/stable      422  10.0.193.116  no       
kfp-api                                             active      1  kfp-api                  2.0/stable      1283  10.0.162.128  no       
kfp-db                     8.0.36-0ubuntu0.22.04.1  active      1  mysql-k8s                8.0/stable       153  10.0.7.99     no       
kfp-metadata-writer                                 active      1  kfp-metadata-writer      2.0/stable       334  10.0.96.190   no       
kfp-persistence                                     active      1  kfp-persistence          2.0/stable      1291  10.0.228.27   no       
kfp-profile-controller                              active      1  kfp-profile-controller   2.0/stable      1315  10.0.54.172   no       
kfp-schedwf                                         active      1  kfp-schedwf              2.0/stable      1466  10.0.211.104  no       
kfp-ui                                              active      1  kfp-ui                   2.0/stable      1285  10.0.236.8    no       
kfp-viewer                                          active      1  kfp-viewer               2.0/stable      1317  10.0.20.142   no       
kfp-viz                                             active      1  kfp-viz                  2.0/stable      1235  10.0.195.109  no       
knative-eventing                                    active      1  knative-eventing         1.10/stable      353  10.0.15.30    no       
knative-operator                                    active      1  knative-operator         1.10/stable      328  10.0.30.18    no       
knative-serving                                     active      1  knative-serving          1.10/stable      409  10.0.235.243  no       
kserve-controller                                   active      1  kserve-controller        0.11/stable      523  10.0.133.162  no       
kubeflow-dashboard                                  active      1  kubeflow-dashboard       1.8/stable       582  10.0.46.190   no       
kubeflow-profiles                                   active      1  kubeflow-profiles        1.8/stable       355  10.0.240.56   no       
kubeflow-roles                                      active      1  kubeflow-roles           1.8/stable       187  10.0.247.9    no       
kubeflow-volumes           res:oci-image@2261827    active      1  kubeflow-volumes         1.8/stable       260  10.0.37.40    no       
metacontroller-operator                             active      1  metacontroller-operator  3.0/stable       252  10.0.185.47   no       
minio                      res:oci-image@1755999    active      1  minio                    ckf-1.8/stable   278  10.0.55.52    no       
mlflow-mysql               8.0.36-0ubuntu0.22.04.1  active      1  mysql-k8s                8.0/stable       153  10.0.232.225  no       
mlflow-server                                       active      1  mlflow-server            2.1/stable       466  10.0.117.149  no       
mlmd                       res:oci-image@44abc5d    active      1  mlmd                     1.14/stable      127  10.0.79.195   no       
oidc-gatekeeper                                     active      1  oidc-gatekeeper          ckf-1.8/stable   350  10.0.111.155  no       
pvcviewer-operator                                  active      1  pvcviewer-operator       1.8/stable        30  10.0.146.105  no       
resource-dispatcher                                 active      1  resource-dispatcher      1.0/stable        93  10.0.81.91    no       
seldon-controller-manager                           active      1  seldon-core              1.17/stable      664  10.0.2.218    no       
tensorboard-controller                              active      1  tensorboard-controller   1.8/stable       257  10.0.137.178  no       
tensorboards-web-app                                active      1  tensorboards-web-app     1.8/stable       245  10.0.190.230  no       
training-operator                                   active      1  training-operator        1.7/stable       347  10.0.239.121  no       

Unit                          Workload  Agent  Address      Ports          Message
admission-webhook/0*          active    idle   10.244.1.19                 
argo-controller/0*            active    idle   10.244.1.15                 
dex-auth/0*                   active    idle   10.244.0.24                 
envoy/0*                      active    idle   10.244.0.36  9090,9901/TCP  
grafana-agent-k8s/0*          active    idle   10.244.0.20                 logging-consumer: off
istio-ingressgateway/0*       active    idle   10.244.1.17                 
istio-pilot/0*                active    idle   10.244.1.13                 
jupyter-controller/0*         active    idle   10.244.1.9                  
jupyter-ui/0*                 active    idle   10.244.0.15                 
katib-controller/0*           active    idle   10.244.1.32  443,8080/TCP   
katib-db-manager/0*           active    idle   10.244.2.10                 
katib-db/0*                   active    idle   10.244.1.16                 Primary
katib-ui/0*                   active    idle   10.244.2.14                 
kfp-api/0*                    active    idle   10.244.1.10                 
kfp-db/0*                     active    idle   10.244.2.19                 Primary
kfp-metadata-writer/0*        active    idle   10.244.1.20                 
kfp-persistence/0*            active    idle   10.244.0.14                 
kfp-profile-controller/0*     active    idle   10.244.2.16                 
kfp-schedwf/0*                active    idle   10.244.1.8                  
kfp-ui/0*                     active    idle   10.244.0.19                 
kfp-viewer/0*                 active    idle   10.244.2.12                 
kfp-viz/0*                    active    idle   10.244.2.11                 
knative-eventing/0*           active    idle   10.244.1.14                 
knative-operator/0*           active    idle   10.244.1.21                 
knative-serving/0*            active    idle   10.244.1.7                  
kserve-controller/0*          active    idle   10.244.0.16                 
kubeflow-dashboard/0*         active    idle   10.244.2.8                  
kubeflow-profiles/0*          active    idle   10.244.1.11                 
kubeflow-roles/0*             active    idle   10.244.0.12                 
kubeflow-volumes/2*           active    idle   10.244.2.6   5000/TCP       
metacontroller-operator/0*    active    idle   10.244.1.18                 
minio/0*                      active    idle   10.244.2.24  9000-9001/TCP  
mlflow-mysql/0*               active    idle   10.244.0.22                 Primary
mlflow-server/0*              active    idle   10.244.0.21                 
mlmd/0*                       active    idle   10.244.2.23  8080/TCP       
oidc-gatekeeper/0*            active    idle   10.244.2.15                 
pvcviewer-operator/0*         active    idle   10.244.1.12                 
resource-dispatcher/0*        active    idle   10.244.0.17                 
seldon-controller-manager/0*  active    idle   10.244.2.13                 
tensorboard-controller/0*     active    idle   10.244.2.7                  
tensorboards-web-app/0*       active    idle   10.244.0.23                 
training-operator/0*          active    idle   10.244.0.18
```

Then I have setup python3.8 with tox 
```
sudo add-apt-repository ppa:deadsnakes/ppa -y
sudo apt update -y
sudo apt install python3.8 python3.8-distutils python3.8-venv -y
wget https://bootstrap.pypa.io/get-pip.py
python3.8 get-pip.py
python3.8 -m pip install tox
export PATH=$PATH:/home/ubuntu/.local/bin
tox --version
```

Then I have cloned UATs repo and run the UATs from `main` branch
```
git clone https://github.com/canonical/charmed-kubeflow-uats.git
cd charmed-kubeflow-uats/
git checkout main 
tox -e kubeflow-remote
```

Test passed 
```
platform linux -- Python 3.8.10, pytest-8.2.2, pluggy-1.5.0 -- /opt/conda/bin/python3.8
cachedir: .pytest_cache
rootdir: /tests/.worktrees/fe86b4e255c4c695376f70061a6a645301350d5a/tests
configfile: pytest.ini
plugins: anyio-3.6.2
collecting ... collected 9 items / 4 deselected / 5 selected

test_notebooks.py::test_notebook[katib-integration] 
-------------------------------- live log call ---------------------------------
INFO     test_notebooks:test_notebooks.py:44 Running katib-integration.ipynb...
PASSED                                                                   [ 20%]
test_notebooks.py::test_notebook[kfp-v1-integration] 
-------------------------------- live log call ---------------------------------
INFO     test_notebooks:test_notebooks.py:44 Running kfp-v1-integration.ipynb...
PASSED                                                                   [ 40%]
test_notebooks.py::test_notebook[kfp-v2-integration] 
-------------------------------- live log call ---------------------------------
INFO     test_notebooks:test_notebooks.py:44 Running kfp-v2-integration.ipynb...
PASSED                                                                   [ 60%]
test_notebooks.py::test_notebook[kserve-integration] 
-------------------------------- live log call ---------------------------------
INFO     test_notebooks:test_notebooks.py:44 Running kserve-integration.ipynb...
PASSED                                                                   [ 80%]
test_notebooks.py::test_notebook[training-integration] 
-------------------------------- live log call ---------------------------------
INFO     test_notebooks:test_notebooks.py:44 Running training-integration.ipynb...
PASSED                                                                   [100%]

================= 5 passed, 4 deselected in 1087.81s (0:18:07) =================
PASSED
--------------------------------------------------------------------------------------------- live log teardown ----------------------------------------------------------------------------------------------
INFO     test_kubeflow_workloads:test_kubeflow_workloads.py:82 Deleting Profile test-kubeflow...
INFO     httpx:_client.py:1013 HTTP Request: DELETE https://kubeflow-n577396o.hcp.uksouth.azmk8s.io/apis/kubeflow.org/v1/profiles/test-kubeflow "HTTP/1.1 200 OK"
INFO     test_kubeflow_workloads:test_kubeflow_workloads.py:141 Deleting Job test-kubeflow/test-kubeflow...
INFO     httpx:_client.py:1013 HTTP Request: DELETE https://kubeflow-n577396o.hcp.uksouth.azmk8s.io/apis/batch/v1/namespaces/test-kubeflow/jobs/test-kubeflow "HTTP/1.1 200 OK"


======================================================================================= 2 passed in 1154.07s (0:19:14) =======================================================================================
  kubeflow-remote: OK (1178.19=setup[22.82]+cmd[1155.36] seconds)
  congratulations :) (1178.33 seconds)
```

Here is the pods log showing no problems
```
ubuntu@vu34wtsmbwx56BootstrapVm:~$ kubectl get po -n test-kubeflow --watch
NAME                                              READY   STATUS            RESTARTS   AGE
ml-pipeline-ui-artifact-6b89ccc469-2b72n          2/2     Running           0          48s
ml-pipeline-visualizationserver-955b54775-nkvg8   0/2     PodInitializing   0          48s
test-kubeflow-dx6vv                               2/2     Running           0          49s
cmaes-example-cmaes-75f5b9d5dd-r8m8k              0/1     Pending           0          0s
cmaes-example-cmaes-75f5b9d5dd-r8m8k              0/1     Pending           0          0s
cmaes-example-cmaes-75f5b9d5dd-r8m8k              0/1     ContainerCreating   0          0s
cmaes-example-cmaes-75f5b9d5dd-r8m8k              0/1     Running             0          5s
cmaes-example-cmaes-75f5b9d5dd-r8m8k              1/1     Running             0          21s
cmaes-example-4qnb4dgb-6fzmt                      0/2     Pending             0          0s
cmaes-example-4qnb4dgb-6fzmt                      0/2     Pending             0          0s
cmaes-example-bzqd6kft-f6rvw                      0/2     Pending             0          0s
cmaes-example-bzqd6kft-f6rvw                      0/2     Pending             0          0s
cmaes-example-4qnb4dgb-6fzmt                      0/2     ContainerCreating   0          0s
cmaes-example-bzqd6kft-f6rvw                      0/2     ContainerCreating   0          0s
ml-pipeline-visualizationserver-955b54775-nkvg8   1/2     Running             0          111s
ml-pipeline-visualizationserver-955b54775-nkvg8   2/2     Running             0          111s
cmaes-example-4qnb4dgb-6fzmt                      2/2     Running             0          42s
cmaes-example-bzqd6kft-f6rvw                      2/2     Running             0          45s
cmaes-example-bzqd6kft-f6rvw                      1/2     NotReady            0          90s
cmaes-example-bzqd6kft-f6rvw                      0/2     Completed           0          92s
cmaes-example-bzqd6kft-f6rvw                      0/2     Completed           0          93s
cmaes-example-bzqd6kft-f6rvw                      0/2     Completed           0          94s
cmaes-example-bzqd6kft-f6rvw                      0/2     Completed           0          94s
cmaes-example-bzqd6kft-f6rvw                      0/2     Terminating         0          94s
cmaes-example-bzqd6kft-f6rvw                      0/2     Terminating         0          94s
cmaes-example-xqr2mc8k-6gn27                      0/2     Pending             0          0s
cmaes-example-xqr2mc8k-6gn27                      0/2     Pending             0          0s
cmaes-example-xqr2mc8k-6gn27                      0/2     ContainerCreating   0          0s
cmaes-example-4qnb4dgb-6fzmt                      1/2     NotReady            0          95s
cmaes-example-4qnb4dgb-6fzmt                      0/2     Completed           0          96s
cmaes-example-xqr2mc8k-6gn27                      2/2     Running             0          2s
cmaes-example-4qnb4dgb-6fzmt                      0/2     Completed           0          98s
cmaes-example-4qnb4dgb-6fzmt                      0/2     Completed           0          98s
cmaes-example-4qnb4dgb-6fzmt                      0/2     Completed           0          99s
cmaes-example-4qnb4dgb-6fzmt                      0/2     Terminating         0          99s
cmaes-example-4qnb4dgb-6fzmt                      0/2     Terminating         0          99s
cmaes-example-xqr2mc8k-6gn27                      1/2     NotReady            0          58s
cmaes-example-xqr2mc8k-6gn27                      0/2     Completed           0          60s
cmaes-example-xqr2mc8k-6gn27                      0/2     Completed           0          61s
cmaes-example-xqr2mc8k-6gn27                      0/2     Completed           0          62s
cmaes-example-xqr2mc8k-6gn27                      0/2     Completed           0          62s
cmaes-example-xqr2mc8k-6gn27                      0/2     Terminating         0          62s
cmaes-example-xqr2mc8k-6gn27                      0/2     Terminating         0          62s
cmaes-example-cmaes-75f5b9d5dd-r8m8k              1/1     Terminating         0          2m58s
cmaes-example-cmaes-75f5b9d5dd-r8m8k              0/1     Terminating         0          2m59s
cmaes-example-cmaes-75f5b9d5dd-r8m8k              0/1     Terminating         0          3m
cmaes-example-cmaes-75f5b9d5dd-r8m8k              0/1     Terminating         0          3m
cmaes-example-cmaes-75f5b9d5dd-r8m8k              0/1     Terminating         0          3m
calculation-pipeline-wkrc2-4050137206             0/2     Pending             0          0s
calculation-pipeline-wkrc2-4050137206             0/2     Pending             0          0s
calculation-pipeline-wkrc2-4050137206             0/2     Init:0/1            0          0s
calculation-pipeline-wkrc2-3212673545             0/2     Pending             0          0s
calculation-pipeline-wkrc2-3212673545             0/2     Pending             0          0s
calculation-pipeline-wkrc2-3212673545             0/2     Init:0/1            0          0s
calculation-pipeline-wkrc2-4050137206             0/2     Init:0/1            0          0s
calculation-pipeline-wkrc2-3212673545             0/2     Init:0/1            0          0s
calculation-pipeline-wkrc2-4050137206             0/2     Init:0/1            0          8s
calculation-pipeline-wkrc2-3212673545             0/2     Init:0/1            0          9s
calculation-pipeline-wkrc2-4050137206             0/2     PodInitializing     0          9s
calculation-pipeline-wkrc2-3212673545             0/2     PodInitializing     0          10s
calculation-pipeline-wkrc2-4050137206             2/2     Running             0          29s
calculation-pipeline-wkrc2-3212673545             2/2     Running             0          30s
calculation-pipeline-wkrc2-4050137206             2/2     Running             0          30s
calculation-pipeline-wkrc2-4050137206             2/2     Running             0          31s
calculation-pipeline-wkrc2-3212673545             2/2     Running             0          31s
calculation-pipeline-wkrc2-3212673545             2/2     Running             0          31s
calculation-pipeline-wkrc2-3212673545             0/2     Completed           0          35s
calculation-pipeline-wkrc2-4050137206             0/2     Completed           0          35s
calculation-pipeline-wkrc2-3212673545             0/2     Completed           0          37s
calculation-pipeline-wkrc2-4050137206             0/2     Completed           0          37s
calculation-pipeline-wkrc2-4050137206             0/2     Completed           0          37s
calculation-pipeline-wkrc2-3212673545             0/2     Completed           0          37s
calculation-pipeline-wkrc2-3195895926             0/2     Pending             0          0s
calculation-pipeline-wkrc2-3195895926             0/2     Pending             0          0s
calculation-pipeline-wkrc2-3195895926             0/2     Init:0/1            0          0s
calculation-pipeline-wkrc2-4050137206             0/2     Completed           0          39s
calculation-pipeline-wkrc2-3212673545             0/2     Completed           0          39s
calculation-pipeline-wkrc2-3195895926             0/2     Init:0/1            0          0s
calculation-pipeline-wkrc2-3195895926             0/2     Init:0/1            0          1s
calculation-pipeline-wkrc2-3195895926             0/2     PodInitializing     0          2s
calculation-pipeline-wkrc2-3195895926             2/2     Running             0          3s
calculation-pipeline-wkrc2-3195895926             1/2     NotReady            0          4s
calculation-pipeline-wkrc2-3195895926             1/2     NotReady            0          4s
calculation-pipeline-wkrc2-3195895926             1/2     NotReady            0          5s
calculation-pipeline-wkrc2-3195895926             0/2     Completed           0          5s
calculation-pipeline-wkrc2-3195895926             0/2     Completed           0          6s
calculation-pipeline-wkrc2-3195895926             0/2     Completed           0          7s
calculation-pipeline-wkrc2-3195895926             0/2     Completed           0          10s
condition-v2-x6h2p-502777903                      0/2     Pending             0          0s
condition-v2-x6h2p-502777903                      0/2     Pending             0          0s
condition-v2-x6h2p-502777903                      0/2     Init:0/1            0          0s
condition-v2-x6h2p-502777903                      0/2     PodInitializing     0          1s
condition-v2-x6h2p-502777903                      2/2     Running             0          6s
condition-v2-x6h2p-502777903                      2/2     Running             0          7s
condition-v2-x6h2p-502777903                      0/2     Completed           0          7s
condition-v2-x6h2p-502777903                      0/2     Completed           0          9s
condition-v2-x6h2p-502777903                      0/2     Completed           0          9s
condition-v2-x6h2p-3683981472                     0/2     Pending             0          0s
condition-v2-x6h2p-3683981472                     0/2     Pending             0          0s
condition-v2-x6h2p-3683981472                     0/2     Init:0/1            0          0s
condition-v2-x6h2p-502777903                      0/2     Completed           0          10s
condition-v2-x6h2p-3683981472                     0/2     PodInitializing     0          1s
condition-v2-x6h2p-3683981472                     2/2     Running             0          2s
condition-v2-x6h2p-3683981472                     1/2     NotReady            0          3s
condition-v2-x6h2p-3683981472                     1/2     NotReady            0          4s
condition-v2-x6h2p-3683981472                     0/2     Completed           0          4s
condition-v2-x6h2p-3683981472                     0/2     Completed           0          6s
condition-v2-x6h2p-3683981472                     0/2     Completed           0          6s
condition-v2-x6h2p-135267782                      0/2     Pending             0          0s
condition-v2-x6h2p-135267782                      0/2     Pending             0          0s
condition-v2-x6h2p-135267782                      0/2     Init:0/2            0          0s
condition-v2-x6h2p-3683981472                     0/2     Completed           0          10s
condition-v2-x6h2p-135267782                      0/2     Init:1/2            0          1s
condition-v2-x6h2p-135267782                      0/2     Init:1/2            0          5s
condition-v2-x6h2p-135267782                      0/2     PodInitializing     0          6s
condition-v2-x6h2p-135267782                      2/2     Running             0          7s
condition-v2-x6h2p-135267782                      0/2     Completed           0          14s
condition-v2-x6h2p-135267782                      0/2     Completed           0          16s
condition-v2-x6h2p-135267782                      0/2     Completed           0          16s
condition-v2-x6h2p-884988224                      0/2     Pending             0          0s
condition-v2-x6h2p-884988224                      0/2     Pending             0          0s
condition-v2-x6h2p-884988224                      0/2     Init:0/1            0          0s
condition-v2-x6h2p-756913840                      0/2     Pending             0          0s
condition-v2-x6h2p-756913840                      0/2     Pending             0          0s
condition-v2-x6h2p-756913840                      0/2     Init:0/1            0          0s
condition-v2-x6h2p-135267782                      0/2     Completed           0          25s
condition-v2-x6h2p-884988224                      0/2     PodInitializing     0          2s
condition-v2-x6h2p-884988224                      2/2     Running             0          3s
condition-v2-x6h2p-884988224                      1/2     NotReady            0          4s
condition-v2-x6h2p-884988224                      1/2     NotReady            0          4s
condition-v2-x6h2p-884988224                      0/2     Completed           0          5s
condition-v2-x6h2p-884988224                      0/2     Completed           0          6s
condition-v2-x6h2p-884988224                      0/2     Completed           0          7s
condition-v2-x6h2p-756913840                      0/2     Init:0/1            0          8s
condition-v2-x6h2p-884988224                      0/2     Completed           0          10s
condition-v2-x6h2p-756913840                      0/2     PodInitializing     0          10s
condition-v2-x6h2p-756913840                      2/2     Running             0          14s
condition-v2-x6h2p-756913840                      2/2     Running             0          15s
condition-v2-x6h2p-756913840                      0/2     Completed           0          16s
condition-v2-x6h2p-756913840                      0/2     Completed           0          17s
condition-v2-x6h2p-756913840                      0/2     Completed           0          18s
condition-v2-x6h2p-3477408950                     0/2     Pending             0          0s
condition-v2-x6h2p-3477408950                     0/2     Pending             0          0s
condition-v2-x6h2p-3477408950                     0/2     Init:0/2            0          0s
condition-v2-x6h2p-756913840                      0/2     Completed           0          20s
condition-v2-x6h2p-3477408950                     0/2     Init:1/2            0          2s
condition-v2-x6h2p-3477408950                     0/2     PodInitializing     0          3s
condition-v2-x6h2p-3477408950                     2/2     Running             0          4s
condition-v2-x6h2p-3477408950                     0/2     Completed           0          11s
condition-v2-x6h2p-3477408950                     0/2     Completed           0          12s
condition-v2-x6h2p-3477408950                     0/2     Completed           0          13s
condition-v2-x6h2p-3477408950                     0/2     Completed           0          21s
sklearn-iris-predictor-00001-deployment-6f6f6bc97b-4qmp8   0/2     Pending             0          0s
sklearn-iris-predictor-00001-deployment-6f6f6bc97b-4qmp8   0/2     Pending             0          0s
sklearn-iris-predictor-00001-deployment-6f6f6bc97b-4qmp8   0/2     Init:0/1            0          0s
sklearn-iris-predictor-00001-deployment-6f6f6bc97b-4qmp8   0/2     Init:0/1            0          15s
sklearn-iris-predictor-00001-deployment-6f6f6bc97b-4qmp8   0/2     PodInitializing     0          26s
sklearn-iris-predictor-00001-deployment-6f6f6bc97b-4qmp8   1/2     Running             0          46s
sklearn-iris-predictor-00001-deployment-6f6f6bc97b-4qmp8   2/2     Running             0          60s
sklearn-iris-predictor-00001-deployment-6f6f6bc97b-4qmp8   2/2     Terminating         0          62s
mnist-chief-0                                              0/1     Pending             0          0s
mnist-chief-0                                              0/1     Pending             0          0s
mnist-chief-0                                              0/1     ContainerCreating   0          0s
mnist-ps-0                                                 0/1     Pending             0          0s
mnist-ps-0                                                 0/1     Pending             0          0s
mnist-ps-0                                                 0/1     ContainerCreating   0          0s
mnist-worker-0                                             0/1     Pending             0          0s
mnist-worker-0                                             0/1     Pending             0          0s
mnist-worker-0                                             0/1     ContainerCreating   0          0s
mnist-worker-1                                             0/1     Pending             0          0s
mnist-worker-1                                             0/1     Pending             0          0s
mnist-worker-1                                             0/1     ContainerCreating   0          0s
sklearn-iris-predictor-00001-deployment-6f6f6bc97b-4qmp8   1/2     Terminating         0          90s
sklearn-iris-predictor-00001-deployment-6f6f6bc97b-4qmp8   0/2     Terminating         0          94s
sklearn-iris-predictor-00001-deployment-6f6f6bc97b-4qmp8   0/2     Terminating         0          94s
sklearn-iris-predictor-00001-deployment-6f6f6bc97b-4qmp8   0/2     Terminating         0          94s
sklearn-iris-predictor-00001-deployment-6f6f6bc97b-4qmp8   0/2     Terminating         0          94s
mnist-chief-0                                              1/1     Running             0          27s
mnist-worker-0                                             1/1     Running             0          27s
mnist-ps-0                                                 1/1     Running             0          28s
mnist-worker-1                                             1/1     Running             0          29s
mnist-worker-0                                             0/1     Completed           0          2m36s
mnist-chief-0                                              0/1     Completed           0          2m37s
mnist-worker-0                                             0/1     Completed           0          2m38s
mnist-chief-0                                              0/1     Completed           0          2m38s
mnist-worker-0                                             0/1     Completed           0          2m38s
mnist-chief-0                                              0/1     Completed           0          2m39s
mnist-worker-0                                             0/1     Terminating         0          3m
mnist-worker-1                                             1/1     Terminating         0          3m
mnist-chief-0                                              0/1     Terminating         0          3m
mnist-chief-0                                              0/1     Terminating         0          3m
mnist-ps-0                                                 1/1     Terminating         0          3m
mnist-worker-0                                             0/1     Terminating         0          3m
pytorch-mnist-gloo-master-0                                0/1     Pending             0          0s
pytorch-mnist-gloo-master-0                                0/1     Pending             0          0s
pytorch-mnist-gloo-master-0                                0/1     ContainerCreating   0          0s
pytorch-mnist-gloo-worker-0                                0/1     Pending             0          0s
pytorch-mnist-gloo-worker-0                                0/1     Pending             0          0s
pytorch-mnist-gloo-worker-0                                0/1     Init:0/1            0          0s
mnist-ps-0                                                 0/1     Terminating         0          3m3s
mnist-ps-0                                                 0/1     Terminating         0          3m3s
mnist-ps-0                                                 0/1     Terminating         0          3m3s
mnist-ps-0                                                 0/1     Terminating         0          3m3s
mnist-worker-1                                             0/1     Terminating         0          3m3s
mnist-worker-1                                             0/1     Terminating         0          3m4s
mnist-worker-1                                             0/1     Terminating         0          3m4s
mnist-worker-1                                             0/1     Terminating         0          3m4s
pytorch-mnist-gloo-master-0                                1/1     Running             0          78s
pytorch-mnist-gloo-worker-0                                0/1     Init:0/1            0          80s
pytorch-mnist-gloo-worker-0                                0/1     PodInitializing     0          85s
pytorch-mnist-gloo-worker-0                                1/1     Running             0          86s
pytorch-mnist-gloo-worker-0                                0/1     Completed           0          4m26s
pytorch-mnist-gloo-master-0                                0/1     Completed           0          4m27s
pytorch-mnist-gloo-worker-0                                0/1     Completed           0          4m27s
pytorch-mnist-gloo-worker-0                                0/1     Completed           0          4m28s
pytorch-mnist-gloo-master-0                                0/1     Completed           0          4m28s
pytorch-mnist-gloo-master-0                                0/1     Completed           0          4m29s
pytorch-mnist-gloo-worker-0                                0/1     Terminating         0          4m30s
pytorch-mnist-gloo-master-0                                0/1     Terminating         0          4m30s
pytorch-mnist-gloo-worker-0                                0/1     Terminating         0          4m30s
pytorch-mnist-gloo-master-0                                0/1     Terminating         0          4m30s
paddle-simple-cpu-worker-0                                 0/1     Pending             0          0s
paddle-simple-cpu-worker-0                                 0/1     Pending             0          0s
paddle-simple-cpu-worker-0                                 0/1     ContainerCreating   0          0s
paddle-simple-cpu-worker-1                                 0/1     Pending             0          0s
paddle-simple-cpu-worker-1                                 0/1     Pending             0          0s
paddle-simple-cpu-worker-1                                 0/1     ContainerCreating   0          0s
paddle-simple-cpu-worker-1                                 1/1     Running             0          78s
paddle-simple-cpu-worker-0                                 1/1     Running             0          79s
paddle-simple-cpu-worker-0                                 0/1     Completed           0          96s
paddle-simple-cpu-worker-1                                 0/1     Completed           0          96s
paddle-simple-cpu-worker-0                                 0/1     Completed           0          98s
paddle-simple-cpu-worker-1                                 0/1     Completed           0          98s
paddle-simple-cpu-worker-1                                 0/1     Completed           0          98s
paddle-simple-cpu-worker-0                                 0/1     Completed           0          98s
paddle-simple-cpu-worker-1                                 0/1     Terminating         0          2m
paddle-simple-cpu-worker-0                                 0/1     Terminating         0          2m
paddle-simple-cpu-worker-1                                 0/1     Terminating         0          2m
paddle-simple-cpu-worker-0                                 0/1     Terminating         0          2m
test-kubeflow-dx6vv                                        1/2     NotReady            0          18m
test-kubeflow-dx6vv                                        0/2     Completed           0          19m
test-kubeflow-dx6vv                                        0/2     Completed           0          19m
test-kubeflow-dx6vv                                        0/2     Completed           0          19m
test-kubeflow-dx6vv                                        0/2     Completed           0          19m
test-kubeflow-dx6vv                                        0/2     Completed           0          19m
calculation-pipeline-wkrc2-3195895926                      0/2     Terminating         0          14m
calculation-pipeline-wkrc2-3195895926                      0/2     Terminating         0          14m
calculation-pipeline-wkrc2-3212673545                      0/2     Terminating         0          14m
calculation-pipeline-wkrc2-3212673545                      0/2     Terminating         0          14m
calculation-pipeline-wkrc2-4050137206                      0/2     Terminating         0          14m
calculation-pipeline-wkrc2-4050137206                      0/2     Terminating         0          14m
condition-v2-x6h2p-135267782                               0/2     Terminating         0          13m
condition-v2-x6h2p-135267782                               0/2     Terminating         0          13m
condition-v2-x6h2p-3477408950                              0/2     Terminating         0          12m
condition-v2-x6h2p-3477408950                              0/2     Terminating         0          12m
condition-v2-x6h2p-3683981472                              0/2     Terminating         0          13m
condition-v2-x6h2p-3683981472                              0/2     Terminating         0          13m
condition-v2-x6h2p-502777903                               0/2     Terminating         0          13m
condition-v2-x6h2p-502777903                               0/2     Terminating         0          13m
condition-v2-x6h2p-756913840                               0/2     Terminating         0          13m
condition-v2-x6h2p-756913840                               0/2     Terminating         0          13m
condition-v2-x6h2p-884988224                               0/2     Terminating         0          13m
condition-v2-x6h2p-884988224                               0/2     Terminating         0          13m
ml-pipeline-ui-artifact-6b89ccc469-2b72n                   2/2     Terminating         0          19m
ml-pipeline-visualizationserver-955b54775-nkvg8            2/2     Terminating         0          19m
test-kubeflow-dx6vv                                        0/2     Terminating         0          19m
test-kubeflow-dx6vv                                        0/2     Terminating         0          19m
ml-pipeline-visualizationserver-955b54775-nkvg8            0/2     Terminating         0          19m
ml-pipeline-ui-artifact-6b89ccc469-2b72n                   0/2     Terminating         0          19m
ml-pipeline-ui-artifact-6b89ccc469-2b72n                   0/2     Terminating         0          19m
ml-pipeline-ui-artifact-6b89ccc469-2b72n                   0/2     Terminating         0          19m
ml-pipeline-ui-artifact-6b89ccc469-2b72n                   0/2     Terminating         0          19m
ml-pipeline-visualizationserver-955b54775-nkvg8            0/2     Terminating         0          19m
ml-pipeline-visualizationserver-955b54775-nkvg8            0/2     Terminating         0          19m
ml-pipeline-visualizationserver-955b54775-nkvg8            0/2     Terminating         0          19m
```

Here is the experiments log without problems
```
ubuntu@vu34wtsmbwx56BootstrapVm:~$ kubectl get experiment -n test-kubeflow --watch
NAME            TYPE      STATUS   AGE
cmaes-example   Created   True     19s
cmaes-example   Running   True     22s
cmaes-example   Running   True     22s
cmaes-example   Running   True     22s
cmaes-example   Running   True     116s
cmaes-example   Running   True     116s
cmaes-example   Running   True     116s
cmaes-example   Running   True     2m1s
cmaes-example   Running   True     2m1s
cmaes-example   Succeeded   True     2m58s
cmaes-example   Succeeded   True     3m5s
cmaes-example   Succeeded   True     3m5s
```

I have run the test twice without problems.

**Comment by misohu** [comment]
After further investigation we found out that the error was caused by running the tox env in python3.10. Switching to 3.8 resolved the issue. The tests are supposed to be executed on python3.8.

**Comment by misohu** [comment]
I have created https://github.com/canonical/charmed-kubeflow-uats/issues/79 to track effort for fixing 3.10 issue.

**Comment by kimwnasptd** [comment]
While doing a workshop dry run, in which we deployed 4 CKFs with the one-click we managed to reproduce the issue.

The root problem was that PodDefaults were not being created in the user namespace. You can see the relevant logs from `metacontroller-operator-charm-0` here:
```
{"level":"info","ts":1720083468.0555964,"msg":"Configuration information","discovery-interval":3600,"cache-flush-interval":1800,"metrics-address":":9999","client-go-qps":5,"client-go-burst":10,"workers":5,"events-qps":0.0033333333333333335,"events-burst":25,"pprofAddr":"0","leader-election":false,"leader-election-resource-lock":"leases","leader-election-namespace":"","leader-election-id":"metacontroller","version":"dev"}
{"level":"info","ts":1720083468.0904067,"msg":"Communication with K8s API server successful"}
{"level":"info","ts":1720083469.291709,"msg":"Waited for 1.188117648s due to client-side throttling, not priority and fairness, request: GET:https://10.0.0.1:443/apis/policy/v1?timeout=32s\n"}
{"level":"info","ts":1720083474.4940627,"logger":"controller-runtime.metrics","msg":"Metrics server is starting to listen","addr":":9999"}
{"level":"info","ts":1720083474.4990547,"msg":"Starting server","path":"/metrics","kind":"metrics","addr":"[::]:9999"}
{"level":"info","ts":1720083474.4995284,"logger":"controller.composite-metacontroller","msg":"Starting EventSource","source":"kind source: *v1alpha1.CompositeController"}
{"level":"info","ts":1720083474.499764,"logger":"controller.composite-metacontroller","msg":"Starting Controller"}
{"level":"info","ts":1720083474.500201,"logger":"controller.decorator-metacontroller","msg":"Starting EventSource","source":"kind source: *v1alpha1.DecoratorController"}
{"level":"info","ts":1720083474.5003712,"logger":"controller.decorator-metacontroller","msg":"Starting Controller"}
{"level":"info","ts":1720083474.7065039,"logger":"controller.decorator-metacontroller","msg":"Starting workers","worker count":1}
{"level":"info","ts":1720083474.8021584,"logger":"controller.composite-metacontroller","msg":"Starting workers","worker count":1}
{"level":"info","ts":1720083479.3033295,"msg":"Waited for 4.794092418s due to client-side throttling, not priority and fairness, request: GET:https://10.0.0.1:443/apis/discovery.k8s.io/v1?timeout=32s\n"}
{"level":"Level(-4)","ts":1720083512.228762,"logger":"decorator","msg":"Sync DecoratorController","name":"kubeflow-resource-dispatcher-controller"}
{"level":"error","ts":1720083512.2290668,"logger":"controller.decorator-metacontroller","msg":"Reconciler error","name":"kubeflow-resource-dispatcher-controller","namespace":"","error":"can't find child resource \"poddefaults\" in kubeflow.org/v1alpha1","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/root/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/root/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:227"}
{"level":"Level(-4)","ts":1720083512.2585924,"logger":"decorator","msg":"Sync DecoratorController","name":"kubeflow-resource-dispatcher-controller"}
{"level":"error","ts":1720083512.2588701,"logger":"controller.decorator-metacontroller","msg":"Reconciler error","name":"kubeflow-resource-dispatcher-controller","namespace":"","error":"can't find child resource \"poddefaults\" in kubeflow.org/v1alpha1","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/root/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/root/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:227"}
{"level":"Level(-4)","ts":1720083512.2736049,"logger":"decorator","msg":"Sync DecoratorController","name":"kubeflow-resource-dispatcher-controller"}
...
{"level":"Level(-4)","ts":1720083630.137914,"logger":"decorator","msg":"Sync DecoratorController","name":"kubeflow-pipelines-profile-controller"}
{"level":"Level(-4)","ts":1720083630.138196,"msg":"Starting shared informer","resource":"namespaces","api_version":"v1"}
{"level":"Level(-4)","ts":1720083630.1382527,"msg":"Starting shared informer","resource":"secrets","api_version":"v1"}
{"level":"Level(-4)","ts":1720083630.1382809,"msg":"Starting shared informer","resource":"configmaps","api_version":"v1"}
{"level":"Level(-4)","ts":1720083630.1383045,"msg":"Starting shared informer","resource":"deployments","api_version":"apps/v1"}
{"level":"Level(-4)","ts":1720083630.1383712,"msg":"Starting shared informer","resource":"services","api_version":"v1"}
{"level":"info","ts":1720083630.139664,"logger":"decorator.kubeflow-pipelines-profile-controller","msg":"Starting DecoratorController","controller":{"apiVersion":"metacontroller.k8s.io/v1alpha1","kind":"DecoratorController","name":"kubeflow-pipelines-profile-controller"}}
{"level":"info","ts":1720083630.142399,"logger":"decorator.kubeflow-pipelines-profile-controller","msg":"Waiting for DecoratorController caches to sync","controller":{"apiVersion":"metacontroller.k8s.io/v1alpha1","kind":"DecoratorController","name":"kubeflow-pipelines-profile-controller"}}
{"level":"info","ts":1720083630.1424806,"msg":"Waiting for caches to sync for kubeflow-pipelines-profile-controller\n"}
{"level":"info","ts":1720083630.342726,"msg":"Caches are synced for kubeflow-pipelines-profile-controller \n"}
{"level":"Level(-4)","ts":1720083676.1224983,"logger":"decorator","msg":"Sync DecoratorController","name":"kubeflow-resource-dispatcher-controller"}
{"level":"error","ts":1720083676.122969,"logger":"controller.decorator-metacontroller","msg":"Reconciler error","name":"kubeflow-resource-dispatcher-controller","namespace":"","error":"can't find child resource \"poddefaults\" in kubeflow.org/v1alpha1","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/root/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/root/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:227"}
{"level":"Level(-4)","ts":1720083839.9631407,"logger":"decorator","msg":"Sync DecoratorController","name":"kubeflow-resource-dispatcher-controller"}
{"level":"error","ts":1720083839.9634733,"logger":"controller.decorator-metacontroller","msg":"Reconciler error","name":"kubeflow-resource-dispatcher-controller","namespace":"","error":"can't find child resource \"poddefaults\" in kubeflow.org/v1alpha1","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/root/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/root/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:227"}
{"level":"Level(-4)","ts":1720083977.063396,"logger":"decorator.kubeflow-pipelines-profile-controller","msg":"Sync","object":{"name":"admin"}}
{"level":"Level(-4)","ts":1720083977.0636435,"logger":"decorator.kubeflow-pipelines-profile-controller","msg":"DecoratorController sync","controller":{"apiVersion":"metacontroller.k8s.io/v1alpha1","kind":"DecoratorController","name":"kubeflow-pipelines-profile-controller"},"parent":{"apiVersion":"v1","kind":"Namespace","name":"admin"}}
{"level":"info","ts":1720083977.076975,"logger":"KubeAPIWarningLogger","msg":"unknown field \"status.kubeflow-pipelines-ready\""}
{"level":"Level(-4)","ts":1720083977.0772133,"logger":"decorator.kubeflow-pipelines-profile-controller","msg":"DecoratorController updating","controller":{"apiVersion":"metacontroller.k8s.io/v1alpha1","kind":"DecoratorController","name":"kubeflow-pipelines-profile-controller"},"parent":{"apiVersion":"v1","kind":"Namespace","name":"admin"}}
{"level":"info","ts":1720083977.0825257,"msg":"Creating","parent":{"apiVersion":"v1","kind":"Namespace","name":"admin"},"child":{"apiVersion":"security.istio.io/v1beta1","kind":"AuthorizationPolicy","namespace":"admin","name":"ns-owner-access-istio-charmed"}}
{"level":"info","ts":1720083977.1115553,"msg":"Creating","parent":{"apiVersion":"v1","kind":"Namespace","name":"admin"},"child":{"apiVersion":"v1","kind":"Secret","namespace":"admin","name":"mlpipeline-minio-artifact"}}
...
{"level":"error","ts":1720084055.312855,"msg":"failed to sync kubeflow-pipelines-profile-controller 'v1:Namespace::admin': can't reconcile children for Namespace /admin: discovery: can't find kind PodDefault in apiVersion kubeflow.org/v1alpha1\n","stacktrace":"metacontroller/pkg/controller/decorator.(*decoratorController).worker\n\t/root/parts/metacontroller/build/pkg/controller/decorator/controller.go:296\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\t/root/go/pkg/mod/k8s.io/apimachinery@v0.23.5/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\t/root/go/pkg/mod/k8s.io/apimachinery@v0.23.5/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/root/go/pkg/mod/k8s.io/apimachinery@v0.23.5/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/root/go/pkg/mod/k8s.io/apimachinery@v0.23.5/pkg/util/wait/wait.go:90\nmetacontroller/pkg/controller/decorator.(*decoratorController).Start.func1.1\n\t/root/parts/metacontroller/build/pkg/controller/decorator/controller.go:270"}
{"level":"Level(-4)","ts":1720084135.52715,"logger":"decorator.kubeflow-pipelines-profile-controller","msg":"Sync","object":{"name":"admin"}}
{"level":"Level(-4)","ts":1720084135.527236,"logger":"decorator.kubeflow-pipelines-profile-controller","msg":"DecoratorController sync","controller":{"apiVersion":"metacontroller.k8s.io/v1alpha1","kind":"DecoratorController","name":"kubeflow-pipelines-profile-controller"},"parent":{"apiVersion":"v1","kind":"Namespace","name":"admin"}}
{"level":"Level(-4)","ts":1720084135.5410385,"logger":"decorator.kubeflow-pipelines-profile-controller","msg":"DecoratorController updating","controller":{"apiVersion":"metacontroller.k8s.io/v1alpha1","kind":"DecoratorController","name":"kubeflow-pipelines-profile-controller"},"parent":{"apiVersion":"v1","kind":"Namespace","name":"admin"}}
{"level":"info","ts":1720084135.546495,"msg":"Creating","parent":{"apiVersion":"v1","kind":"Namespace","name":"admin"},"child":{"apiVersion":"security.istio.io/v1beta1","kind":"AuthorizationPolicy","namespace":"admin","name":"ns-owner-access-istio-charmed"}}
{"level":"info","ts":1720084135.5726871,"msg":"Failed to create child, child object already exists","parent":{"apiVersion":"v1","kind":"Namespace","name":"admin"},"child":{"apiVersion":"security.istio.io/v1beta1","kind":"AuthorizationPolicy","namespace":"admin","name":"ns-owner-access-istio-charmed"}}
{"level":"info","ts":1720084135.5733445,"msg":"Updating","parent":{"apiVersion":"v1","kind":"Namespace","name":"admin"},"child":{"apiVersion":"apps/v1","kind":"Deployment","namespace":"admin","name":"ml-pipeline-visualizationserver"},"reason":"InPlace update strategy selected"}
{"level":"info","ts":1720084135.581163,"msg":"Updating","parent":{"apiVersion":"v1","kind":"Namespace","name":"admin"},"child":{"apiVersion":"apps/v1","kind":"Deployment","namespace":"admin","name":"ml-pipeline-ui-artifact"},"reason":"InPlace update strategy selected"}
{"level":"error","ts":1720084135.588662,"msg":"failed to sync kubeflow-pipelines-profile-controller 'v1:Namespace::admin': can't reconcile children for Namespace /admin: discovery: can't find kind PodDefault in apiVersion kubeflow.org/v1alpha1\n","stacktrace":"metacontroller/pkg/controller/decorator.(*decoratorController).worker\n\t/root/parts/metacontroller/build/pkg/controller/decorator/controller.go:296\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\t/root/go/pkg/mod/k8s.io/apimachinery@v0.23.5/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\t/root/go/pkg/mod/k8s.io/apimachinery@v0.23.5/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/root/go/pkg/mod/k8s.io/apimachinery@v0.23.5/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/root/go/pkg/mod/k8s.io/apimachinery@v0.23.5/pkg/util/wait/wait.go:90\nmetacontroller/pkg/controller/decorator.(*decoratorController).Start.func1.1\n\t/root/parts/metacontroller/build/pkg/controller/decorator/controller.go:270"}
{"level":"Level(-4)","ts":1720084167.6441374,"logger":"decorator","msg":"Sync DecoratorController","name":"kubeflow-resource-dispatcher-controller"}
{"level":"error","ts":1720084167.64454,"logger":"controller.decorator-metacontroller","msg":"Reconciler error","name":"kubeflow-resource-dispatcher-controller","namespace":"","error":"can't find child resource \"poddefaults\" in kubeflow.org/v1alpha1","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/root/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/root/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:227"}
```

The short term solution was to delete the `metacontroller-operator-charm-0` pod. The new one then created the PodDefaults

**Comment by kimwnasptd** [comment]
There's a very high chance that this is related to 
https://github.com/canonical/metacontroller-operator/issues/86

**Comment by misohu** [comment]
Ok I have spent some time today to fix the problem @kimwnasptd think is related. 

Mine first idea for the fix was to deploy decorator controller in `kfp-profile-controller` after the poddefault crd is presented in the cluster. Because of this I have created [crd gate component](https://github.com/canonical/charmed-kubeflow-chisme/pull/115) in chisme which blocks the charm until desired crds are presentd in the cluster. I did the manual tests mentioned in this issue https://github.com/canonical/metacontroller-operator/issues/86 and it was working. 

Then I tried to create [integration test](https://github.com/canonical/kfp-operators/pull/534) with similar behavior which would simulate the behavior. In this test sometimes the problem occurs again.

**Comment by misohu** [comment]
Ok dug through the metacontroller docs ... there is a setting [`discovery-interval`](https://metacontroller.github.io/metacontroller/guide/configuration.html#:~:text=%2D%2D-,discovery%2Dinterval,-How%20often%20to) which we are setting to 3600s this setting specifies how often should the metacontroller check for newly installed resources. This means if the controller is deployed when the poddefault is not there the metacontroller willl update the cached resources in one hour.

Upstream also sets it to 3600s with some weird comment next to it https://github.com/kubeflow/manifests/blob/1.9.0-rc.2/apps/kfp-tekton/upstream/third-party/metacontroller/base/stateful-set.yaml#L31

There are couple of options options rn 
1. We can create the poddefaults gate inside metacontroller and only deploy metacontroller if poddefaults is in the cluster. This option will make metacontroller only deployable with admission webhook which is responsible for pod defaults. 
2. We can create empty relation between metacontroller and admission webhook and block the metacontroller deployment until the relation is present. This is basically same as the previous option implemented just with relation. I prefer the option one as I dont think empty relations without data are ment for this usecase. 
3. We can lover the metacontroller `discovery-time` to something really small and dont implement any gate nor relations. This option will derail the metacontroller in CKF from upstream as upstream uses 3600s interval. Plus I am also worried about the comment from the author next to the setting. Even with setting really low there still might be a chance that the metacontroller will be deployed before poddefaults.

**Comment by kimwnasptd** [comment]
@misohu but if we have this gate it means we make the metacontroller Charm tied to Kubeflow (and its CRDs)

The approach of updating the `discovery-interval` sounds the right one to me, which is what other controllers need to do as well. Setting this to 3600s sounds too loose.

Have we tried updating this and see how it behaves?

**Comment by misohu** [comment]
I have ran small experiment where I have deployed metacontroller with `discovery-interval` equal to 30s then I have dpeloyed metacontroller, profile controller and I deployed namespace where the poddefault should be created. Because the admission webhook with poddefault crd was not present the metacontroller went to the error `missing poddefault crd`. Then I have deployed admission webhook and I was monitoring metacontroller. For 10 minutes nothing happend to the existing namespace ... I could see every 30 seconds logs regarding crd updates in metacontroller but the existing namespace was not fixed. During this time I have created second namespace and this cause to fix the first namespace and both had poddefaults. 

Conclusions 

- We can lower the `discovery-interval` but if the namesapce was created during the time crd was not present the namespace will not be fixed unless the metacontroller pod is restarted or we create a second namespace. 
- Lowering the interval will diverge the charm from upstream which uses 3600s interval
- I am little worried about the upstream [note](https://github.com/kubeflow/manifests/blob/1.9.0-rc.2/apps/kfp-tekton/upstream/third-party/metacontroller/base/stateful-set.yaml#L31) next to the interval. Not sure what does that mean

**Comment by misohu** [comment]
Reopening because we see similar problem in Azure one click deployment. After quick analysis it looks like a different root cause as the poddefaults are correctly created for user namespace and the metacontroller logs are not reporting missing poddefaults.  

New logs from UATS. https://pastebin.canonical.com/p/KVMJTqjFRR/

**Comment by NohaIhab** [comment]
The UATs are still failing on one-click deployment even using the branch from https://github.com/canonical/charmed-kubeflow-uats/pull/117.
The logs from the UATs are:
```
=========================== short test summary info ============================
FAILED test_notebooks.py::test_notebook[e2e-wine-kfp-mlflow-kserve] - Failed: Notebook execution failed with ApiException: (401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'content-type': 'application/json', 'date': 'Wed, 11 Sep 2024 07:38:12 GMT', 'content-length': '811', 'x-envoy-upstream-service-time': '10', 'server': 'envoy'})
HTTP response body: {"error":"List experiments failed: Failed to authorize with API: Failed to authorize with API: Unauthenticated: Failed to check authorization. User identity is empty in the request header: Un
authenticated: Request header error: there is no user identity header.: Request header error: there is no user identity header.","code":16,"message":"List experiments failed: Failed to authorize with API: Failed
 to authorize with API: Unauthenticated: Failed to check authorization. User identity is empty in the request header: Unauthenticated: Request header error: there is no user identity header.: Request header erro
r: there is no user identity header.","details":[{"@type":"type.googleapis.com/google.rpc.Status","code":16,"message":"Failed to check authorization. User identity is empty in the request header"}]}
FAILED test_notebooks.py::test_notebook[kfp-v1-integration] - Failed: Notebook execution failed with ApiException: (401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'content-type': 'application/json', 'date': 'Wed, 11 Sep 2024 07:41:17 GMT', 'content-length': '827', 'x-envoy-upstream-service-time': '4', 'server': 'envoy'})
HTTP response body: {"error":"List v1beta1 experiments failed: Failed to authorize with API: Failed to authorize with API: Unauthenticated: Failed to check authorization. User identity is empty in the request he
ader: Unauthenticated: Request header error: there is no user identity header.: Request header error: there is no user identity header.","code":16,"message":"List v1beta1 experiments failed: Failed to authorize
with API: Failed to authorize with API: Unauthenticated: Failed to check authorization. User identity is empty in the request header: Unauthenticated: Request header error: there is no user identity header.: Req
uest header error: there is no user identity header.","details":[{"@type":"type.googleapis.com/google.rpc.Status","code":16,"message":"Failed to check authorization. User identity is empty in the request header"
}]}
FAILED test_notebooks.py::test_notebook[kfp-v2-integration] - Failed: Notebook execution failed with ApiException: (401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'content-type': 'application/json', 'date': 'Wed, 11 Sep 2024 07:41:34 GMT', 'content-length': '811', 'x-envoy-upstream-service-time': '2', 'server': 'envoy'})
HTTP response body: {"error":"List experiments failed: Failed to authorize with API: Failed to authorize with API: Unauthenticated: Failed to check authorization. User identity is empty in the request header: Un
authenticated: Request header error: there is no user identity header.: Request header error: there is no user identity header.","code":16,"message":"List experiments failed: Failed to authorize with API: Failed
 to authorize with API: Unauthenticated: Failed to check authorization. User identity is empty in the request header: Unauthenticated: Request header error: there is no user identity header.: Request header erro
r: there is no user identity header.","details":[{"@type":"type.googleapis.com/google.rpc.Status","code":16,"message":"Failed to check authorization. User identity is empty in the request header"}]}
FAILED test_notebooks.py::test_notebook[mlflow-kserve] - Failed: Notebook execution failed with AssertionError: Failed to create Inference Service wine-regressor3.
=================== 4 failed, 5 passed in 1204.22s (0:20:04) ===================
FAILED
```
and from the kfp api server workload pod:
```
2024-09-11T11:06:55.153Z [apiserver] I0911 11:06:55.153797      16 interceptor.go:29] /api.ExperimentService/ListExperimentsV1 handler starting
2024-09-11T11:06:55.155Z [apiserver] I0911 11:06:55.154031      16 resource_manager.go:1690] Getting user identity
2024-09-11T11:06:55.155Z [apiserver] E0911 11:06:55.154123      16 error.go:280] Unauthenticated: Request header error: there is no user identity header.: Request header error: there is no user identity header.
2024-09-11T11:06:55.155Z [apiserver] Unauthenticated: Failed to check authorization. User identity is empty in the request header
```
